name: Mergebase SCA Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # 安裝 Python 依賴

    - name: Trigger MergeBase Scan
      id: mergebase_scan
      run: |
        response=$(curl -X GET https://app.mergebase.com/cdAkCZmB7/api/n/scans \
        -H "Authorization: Bearer ${{ secrets.MERGEBASE_API_TOKEN }}")
        echo "Scan response: $response"

    - name: Get MergeBase Scan Report
      run: |
        # 假設 API 返回的 JSON 直接包含報告
        report=$(echo $response | jq -r '.report')  # 根據實際返回的 JSON 結構調整
        echo "Scan Report: $report"
